"""Demo workspace + system user seeding.

All landing-page demo content (pages, sessions, Cartridges generated by
visitors' agents) lands in a single shared 'Demo' workspace owned by
a system user. Each demo Stash is public-but-unlisted, isolated only
by an unguessable slug.

Seeding is idempotent and runs on app startup, alongside the workspace
skill seeds.
"""

from __future__ import annotations

import logging
import os
import secrets
from uuid import UUID

from ..auth import hash_password
from ..database import get_pool
from . import files_tree_service
from .demo_content import (
    ABOUT_STASH_MARKDOWN,
    DEMO_ABOUT_FILENAME,
    DEMO_KB_FOLDER_NAME,
    DEMO_SKILL_FILENAME,
    SLIDES_SKILL_MARKDOWN,
)

logger = logging.getLogger(__name__)

DEMO_SYSTEM_USERNAME = "stash-demo"
DEMO_WORKSPACE_NAME = "Stash Demo Workspace"
DEMO_WORKSPACE_DESCRIPTION = (
    "Public-unlisted demo Cartridges created from the landing-page demo. "
    "Each Stash is isolated by an unguessable slug; the workspace itself "
    "is not enumerable."
)

# Off-switch for tests that want a pristine DB.
DISABLE_ENV_VAR = "STASH_DISABLE_DEMO_SEED"


async def seed_demo_workspace() -> tuple[UUID, UUID] | None:
    """Ensure the Demo system user and workspace exist.

    Returns (workspace_id, owner_user_id), or None if seeding is disabled.
    Idempotent — safe to call on every boot.
    """
    if os.environ.get(DISABLE_ENV_VAR) == "1":
        return None
    pool = get_pool()

    owner_id = await pool.fetchval(
        "SELECT id FROM users WHERE name = $1",
        DEMO_SYSTEM_USERNAME,
    )
    if owner_id is None:
        # Random unrecoverable password — this account is never meant to
        # be logged into; the demo router operates as it via the
        # services directly.
        pw_hash = hash_password(secrets.token_urlsafe(32))
        owner_id = await pool.fetchval(
            "INSERT INTO users (name, display_name, password_hash, description) "
            "VALUES ($1, $2, $3, $4) RETURNING id",
            DEMO_SYSTEM_USERNAME,
            "Stash Demo",
            pw_hash,
            "System user that owns landing-page demo Cartridges.",
        )
        logger.info("created demo system user %s", owner_id)

    workspace_id = await pool.fetchval(
        "SELECT w.id FROM workspaces w "
        "JOIN workspace_members wm ON wm.workspace_id = w.id "
        "WHERE wm.user_id = $1 AND w.name = $2 LIMIT 1",
        owner_id,
        DEMO_WORKSPACE_NAME,
    )
    if workspace_id is None:
        invite_code = secrets.token_urlsafe(6)[:8]
        workspace_id = await pool.fetchval(
            "INSERT INTO workspaces (name, description, creator_id, invite_code) "
            "VALUES ($1, $2, $3, $4) RETURNING id",
            DEMO_WORKSPACE_NAME,
            DEMO_WORKSPACE_DESCRIPTION,
            owner_id,
            invite_code,
        )
        await pool.execute(
            "INSERT INTO workspace_members (workspace_id, user_id, role, is_primary) "
            "VALUES ($1, $2, 'owner', false)",
            workspace_id,
            owner_id,
        )
        logger.info("created demo workspace %s", workspace_id)

    await _seed_kb_folder(workspace_id, owner_id)
    return workspace_id, owner_id


async def _seed_kb_folder(workspace_id: UUID, owner_id: UUID) -> UUID:
    """Ensure the canonical Stash knowledge base folder + two pages exist.

    Every published demo Stash references this single folder so visitors
    receive the slides skill and about-Stash markdown alongside the deck
    and Q&A. One canonical copy, many references.
    """
    pool = get_pool()
    folder_id = await pool.fetchval(
        "SELECT id FROM folders WHERE workspace_id = $1 AND name = $2 "
        "AND parent_folder_id IS NULL LIMIT 1",
        workspace_id,
        DEMO_KB_FOLDER_NAME,
    )
    if folder_id is None:
        folder = await files_tree_service.create_folder(
            workspace_id=workspace_id,
            name=DEMO_KB_FOLDER_NAME,
            created_by=owner_id,
        )
        folder_id = folder["id"]

    await _ensure_kb_page(
        workspace_id, owner_id, folder_id, DEMO_SKILL_FILENAME, SLIDES_SKILL_MARKDOWN
    )
    await _ensure_kb_page(
        workspace_id, owner_id, folder_id, DEMO_ABOUT_FILENAME, ABOUT_STASH_MARKDOWN
    )
    return folder_id


async def _ensure_kb_page(
    workspace_id: UUID,
    owner_id: UUID,
    folder_id: UUID,
    name: str,
    content: str,
) -> None:
    pool = get_pool()
    existing = await pool.fetchval(
        "SELECT id FROM pages WHERE workspace_id = $1 AND folder_id = $2 "
        "AND name = $3 AND deleted_at IS NULL LIMIT 1",
        workspace_id,
        folder_id,
        name,
    )
    if existing is not None:
        return
    await files_tree_service.create_page(
        workspace_id=workspace_id,
        name=name,
        created_by=owner_id,
        folder_id=folder_id,
        content=content,
        content_type="markdown",
    )


async def get_kb_folder_id() -> UUID:
    """Return the canonical KB folder id inside the Demo workspace."""
    workspace_id, _ = await get_demo_workspace()
    pool = get_pool()
    folder_id = await pool.fetchval(
        "SELECT id FROM folders WHERE workspace_id = $1 AND name = $2 "
        "AND parent_folder_id IS NULL LIMIT 1",
        workspace_id,
        DEMO_KB_FOLDER_NAME,
    )
    if folder_id is None:
        raise RuntimeError("Demo KB folder is missing; startup seed did not run")
    return folder_id


async def get_demo_workspace() -> tuple[UUID, UUID]:
    """Resolve (workspace_id, owner_id) for the demo. Raises if missing.

    Callers should rely on `seed_demo_workspace` running at startup; this
    is a fast read used by request handlers.
    """
    pool = get_pool()
    row = await pool.fetchrow(
        "SELECT w.id AS workspace_id, w.creator_id AS owner_id "
        "FROM workspaces w "
        "JOIN users u ON u.id = w.creator_id "
        "WHERE u.name = $1 AND w.name = $2 LIMIT 1",
        DEMO_SYSTEM_USERNAME,
        DEMO_WORKSPACE_NAME,
    )
    if row is None:
        raise RuntimeError("Demo workspace is not seeded. Did startup run " "seed_demo_workspace?")
    return row["workspace_id"], row["owner_id"]
