// Screen: HTML page viewer — page.content_type === 'html'
// A page that renders an HTML artifact (e.g. a research report, a chart, a mockup)
// Notion-style brand banner + title + framed iframe-like content + aside

function HtmlPageScreen() {
  return (
    <AppShell
      breadcrumb={['engineering', 'session-replay mockup']}
      activeSection=""
      activePage="session-replay mockup"
    >
      <div className="scroll-thin" style={{ overflow: 'auto' }}>
        <div className="brand-banner" />
        <div style={{
          maxWidth: 1100, margin: '0 auto', padding: '0 48px 80px',
          display: 'grid', gridTemplateColumns: 'minmax(0, 1fr) 240px', gap: 28, marginTop: -22,
        }}>
          {/* Main */}
          <div style={{ minWidth: 0 }}>
            <span style={{
              width: 56, height: 56, borderRadius: 12,
              background: '#fff', border: '1px solid var(--border-color)',
              display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
              color: 'var(--brand-600)',
            }}>
              <svg viewBox="0 0 24 24" width="28" height="28" fill="none" stroke="currentColor" strokeWidth="1.6">
                <rect x="3" y="4" width="18" height="16" rx="2"/>
                <path d="M3 9h18"/>
                <circle cx="6" cy="6.5" r="0.6" fill="currentColor"/>
                <circle cx="8.2" cy="6.5" r="0.6" fill="currentColor"/>
              </svg>
            </span>
            <h1 style={{
              fontFamily: 'var(--font-display)', fontSize: 34, fontWeight: 700,
              letterSpacing: '-0.02em', margin: '12px 0 6px',
            }}>session-replay mockup.html</h1>
            <div style={{
              display: 'flex', alignItems: 'center', gap: 10, fontSize: 12, color: 'var(--text-muted)',
            }}>
              <span className="tag tag-brand">html</span>
              <span>Last edited May 17 · 11:08 by Henry</span>
              <span>·</span>
              <span style={{ color: 'var(--success)' }}>Saved</span>
              <span style={{ flex: 1 }} />
              <button className="btn btn-sm"><Icon name="Code" /> View source</button>
              <button className="btn btn-sm"><Icon name="Eye" /> Full screen</button>
              <button className="btn btn-sm"><Icon name="Download" /> Download</button>
            </div>

            <p style={{ fontSize: 14, color: 'var(--text-dim)', margin: '16px 0 6px', lineHeight: 1.6 }}>
              Generated by <span style={{ fontFamily: 'var(--font-mono)', color: 'var(--text-primary)' }}>session #henry-claude-3147</span> ·
              edits stream live into the file. Renders in a sandboxed iframe with our default style.
            </p>

            {/* Rendered HTML iframe */}
            <div style={{
              marginTop: 14, borderRadius: 12, overflow: 'hidden',
              border: '1px solid var(--border-color)', background: '#fff',
            }}>
              {/* Toolbar */}
              <div style={{
                height: 32, borderBottom: '1px solid var(--border-color)',
                background: 'var(--bg-surface)', display: 'flex', alignItems: 'center', gap: 6,
                padding: '0 10px', fontSize: 11, color: 'var(--text-muted)',
              }}>
                <span style={{ width: 10, height: 10, borderRadius: 999, background: '#FECACA' }} />
                <span style={{ width: 10, height: 10, borderRadius: 999, background: '#FDE68A' }} />
                <span style={{ width: 10, height: 10, borderRadius: 999, background: '#BBF7D0' }} />
                <span style={{ flex: 1 }} />
                <span style={{ fontFamily: 'var(--font-mono)', fontSize: 10.5 }}>
                  workspace/engineering/session-replay-mockup.html · rendered
                </span>
                <span style={{ flex: 1 }} />
                <span style={{ display: 'inline-flex', gap: 4 }}>
                  <span style={{
                    padding: '1px 6px', background: 'var(--bg-raised)', borderRadius: 3,
                    fontFamily: 'var(--font-mono)', fontSize: 10,
                  }}>desktop</span>
                  <span style={{
                    padding: '1px 6px', background: 'transparent', color: 'var(--text-muted)', borderRadius: 3,
                    fontFamily: 'var(--font-mono)', fontSize: 10,
                  }}>tablet</span>
                  <span style={{
                    padding: '1px 6px', background: 'transparent', color: 'var(--text-muted)', borderRadius: 3,
                    fontFamily: 'var(--font-mono)', fontSize: 10,
                  }}>phone</span>
                </span>
              </div>

              {/* Faux rendered content — a session replay UI */}
              <div style={{ padding: 28, background: '#FAFAF7', minHeight: 460 }}>
                <div style={{ display: 'flex', gap: 18 }}>
                  <div style={{ flex: 2 }}>
                    <div style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 22, color: '#1F2937', letterSpacing: '-0.02em' }}>
                      Session replay · #henry-codex-3148
                    </div>
                    <div style={{ marginTop: 4, fontSize: 11.5, color: '#6B7280', fontFamily: 'var(--font-mono)' }}>
                      14:22:08 → 14:33:12 · 11m 04s · 31 turns
                    </div>

                    {/* Faux timeline */}
                    <div style={{ marginTop: 18, display: 'flex', flexDirection: 'column', gap: 6 }}>
                      {[
                        ['14:22', 'human', 'Wire up MCP cli surface…'],
                        ['14:23', 'tool', 'read_file × 3'],
                        ['14:24', 'agent', 'Plan committed to PLAN.md'],
                        ['14:31', 'tool', 'edit_file server.py'],
                        ['14:32', 'tool', 'run_tests · 8 passed'],
                        ['14:33', 'agent', 'Done. Want TS sdk too?'],
                      ].map(([time, who, what], i) => (
                        <div key={i} style={{
                          display: 'grid', gridTemplateColumns: '60px 60px 1fr', gap: 10, alignItems: 'center',
                          padding: '7px 10px',
                          background: '#fff',
                          border: '1px solid #E5E7EB',
                          borderRadius: 6,
                          fontSize: 12.5,
                        }}>
                          <span style={{ fontFamily: 'var(--font-mono)', color: '#6B7280' }}>{time}</span>
                          <span style={{
                            fontFamily: 'var(--font-mono)', fontSize: 10, textTransform: 'uppercase',
                            color: who === 'agent' ? '#6D28D9' : who === 'tool' ? '#3730A3' : '#1D4ED8',
                            background: who === 'agent' ? '#EDE9FE' : who === 'tool' ? '#EEF2FF' : '#DBEAFE',
                            padding: '1px 5px', borderRadius: 3, display: 'inline-block', textAlign: 'center',
                          }}>{who}</span>
                          <span style={{ color: '#1F2937' }}>{what}</span>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Sidebar in fake page */}
                  <div style={{ flex: 1 }}>
                    <div className="stripe-placeholder" style={{ height: 120 }}>
                      file diff · server.py
                    </div>
                    <div className="stripe-placeholder" style={{ height: 80, marginTop: 10 }}>
                      tool i/o detail
                    </div>
                    <div className="stripe-placeholder" style={{ height: 80, marginTop: 10 }}>
                      cost / trace
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div style={{
              marginTop: 16, display: 'flex', alignItems: 'center', gap: 10,
              fontSize: 11.5, color: 'var(--text-muted)',
            }}>
              <span className="sys-label">SANDBOX</span>
              <span>· this HTML renders in an isolated iframe — script tags allowed, network calls go through stash.</span>
            </div>
          </div>

          {/* Aside */}
          <aside style={{ marginTop: 80, display: 'flex', flexDirection: 'column', gap: 12 }}>
            <div className="card-soft" style={{ padding: 14 }}>
              <div className="sys-label">In stashes</div>
              <div style={{ marginTop: 8, display: 'flex', flexDirection: 'column', gap: 6 }}>
                <a className="linkrow" style={{ padding: '6px 8px' }}>
                  <span style={{ color: 'var(--brand-600)' }}><Icon name="Stash" /></span>
                  <span style={{ fontSize: 12.5, fontWeight: 500, flex: 1 }}>v0 launch prep</span>
                  <span className="sys-label" style={{ fontSize: 10 }}>14</span>
                </a>
              </div>
              <button className="btn btn-sm" style={{ marginTop: 6, width: '100%' }}>
                <Icon name="Plus" /> Add to stash
              </button>
            </div>

            <div className="card-soft" style={{ padding: 14 }}>
              <div className="sys-label">Created by</div>
              <div style={{ marginTop: 8, display: 'flex', alignItems: 'center', gap: 8 }}>
                <span className="avatar av-violet" style={{ width: 22, height: 22, fontSize: 9 }}>AG</span>
                <div style={{ fontSize: 12.5, lineHeight: 1.4 }}>
                  <div style={{ color: 'var(--text-primary)', fontWeight: 500 }}>Claude Code · Sonnet 5</div>
                  <div className="sys-label" style={{ fontSize: 10 }}>session #henry-claude-3147</div>
                </div>
              </div>
            </div>

            <div className="card-soft" style={{ padding: 14 }}>
              <div className="sys-label">Page info</div>
              <div style={{ marginTop: 8, fontSize: 11.5, color: 'var(--text-dim)', lineHeight: 1.8, fontFamily: 'var(--font-mono)' }}>
                <div>path · /engineering/session-replay-mockup.html</div>
                <div>size · 4.2 KB</div>
                <div>edits · 6</div>
                <div>viewed · 23 times</div>
              </div>
            </div>
          </aside>
        </div>
      </div>
    </AppShell>
  );
}

window.HtmlPageScreen = HtmlPageScreen;
